Update offload test to wait for ledgers to be deleted from BookKeeper

diff --git a/helm-chart-sources/pulsar/templates/tests/offload-test.yaml b/helm-chart-sources/pulsar/templates/tests/offload-test.yaml
--- a/helm-chart-sources/pulsar/templates/tests/offload-test.yaml
+++ b/helm-chart-sources/pulsar/templates/tests/offload-test.yaml
@@ -33,12 +33,12 @@ data:
     $PERF_CMD produce -s 10 -r 200 -m 14000 $TOPIC
     exit_if_error $? "Publishing messages failed"
 
-    echo "Manually trigger offload"
-    $ADM_CMD topics offload -s 1 $TOPIC
-    exit_if_error $? "Manually triggering offload failed"
+    #echo "Manually trigger offload"
+    #$ADM_CMD topics offload -s 1 $TOPIC
+    #exit_if_error $? "Manually triggering offload failed"
 
-    echo "Wait for offload to complete"
-    sleep 10
+    echo "Wait for offload to complete and BookKeeper copy to be deleted"
+    sleep 121
 
     echo "Make sure some ledgers are offloaded"
     $ADM_CMD topics stats-internal $TOPIC  | grep '"offloaded" : true'
